// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJthu2hDnrz4GBAnmFDOaSqPKVLA8P9xQ',
    appId: '1:673668549384:web:46c334fc899b7cd8df7abd',
    messagingSenderId: '673668549384',
    projectId: 'maniadochopp',
    authDomain: 'maniadochopp.firebaseapp.com',
    storageBucket: 'maniadochopp.firebasestorage.app',
    measurementId: 'G-HY8Y9SJQZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7CX-gO5ixc7UYqeO_BqrznWVuq5-FSQ',
    appId: '1:673668549384:android:cf6e65e54e23d4bddf7abd',
    messagingSenderId: '673668549384',
    projectId: 'maniadochopp',
    storageBucket: 'maniadochopp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmh-64vpxuY-fklzkk_6O-oVTIy6LZcY',
    appId: '1:673668549384:ios:26f5c1955143c0b2df7abd',
    messagingSenderId: '673668549384',
    projectId: 'maniadochopp',
    storageBucket: 'maniadochopp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEmh-64vpxuY-fklzkk_6O-oVTIy6LZcY',
    appId: '1:673668549384:ios:26f5c1955143c0b2df7abd',
    messagingSenderId: '673668549384',
    projectId: 'maniadochopp',
    storageBucket: 'maniadochopp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJthu2hDnrz4GBAnmFDOaSqPKVLA8P9xQ',
    appId: '1:673668549384:web:419a8dca1aeb13c1df7abd',
    messagingSenderId: '673668549384',
    projectId: 'maniadochopp',
    authDomain: 'maniadochopp.firebaseapp.com',
    storageBucket: 'maniadochopp.firebasestorage.app',
    measurementId: 'G-77TJTK51EF',
  );
}
